# Generated by Django 5.0.3 on 2024-05-13 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='activity',
            field=models.TextField(choices=[('KF', 'Kid Friendly'), ('MU', 'Museums'), ('SPNG', 'Shopping'), ('HST', 'Historical'), ('OAV', 'Outdoor Adventures'), ('ARTC', 'Art & Culture'), ('OT', 'Other')], default='', max_length=255),
            preserve_default=False,
        ),
    ]
