# Generated by Django 5.0.6 on 2024-05-24 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='base.country'),
        ),
        migrations.AlterField(
            model_name='route',
            name='activity',
            field=models.ManyToManyField(blank=True, null=True, to='base.activity'),
        ),
    ]
