# Generated by Django 5.0.6 on 2024-05-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_route_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.TextField(choices=[('KF', 'Kid Friendly'), ('MU', 'Museums'), ('SPNG', 'Shopping'), ('HST', 'Historical'), ('OAV', 'Outdoor Adventures'), ('ARTC', 'Art & Culture'), ('OT', 'Other')], max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='route',
            name='activity',
        ),
        migrations.AddField(
            model_name='route',
            name='activity',
            field=models.ManyToManyField(to='base.activity'),
        ),
    ]
